### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by svw26** [caracal-pipeline/MosaicQueen#16]
Reminder to write extra logic to determine whether a 'missing file' message is raised as an Error or noted as a Warning in the logging. This is connected to the --regrid and --force-regrid arguments (or absence thereof). x

**Comment by svw26** [comment]
(Or just noted as 'Info' again) x

**Comment by paoloserra** [comment]
@svw26 does this still need work? Currently a missing file makes mosaicqueen exit with an error, which I think is OK. Or did you want a different behaviour?

**Comment by svw26** [comment]
I think the current behaviour is fine -- This issue was opened based on a comment from @SpheMakh over the 'mosaic' Slack channel :) x

**Comment by sphemakh** [comment]
I'm trying to remember what my issue was. What is the exit error @paoloserra?

**Comment by paoloserra** [comment]
```
$ mosaic-queen -m spectral -f -i output_short/cubes/cube_1 -t mos_T29R03C01_HI.image.fits -t mos_T29R03C03_HI.image.fits -t BLABLABLA.fits -o mos_output -n issue10 -a -bc 0.1 -mc 0.2
2022-04-12 15:25:33,382 - MAKE_MOSAIC - INFO - Target images = mos_T29R03C01_HI.image.fits mos_T29R03C03_HI.image.fits BLABLABLA.fits
2022-04-12 15:25:33,382 - MAKE_MOSAIC - INFO - Will generate mosaics made from the input images, their associated models, and their residuals
2022-04-12 15:25:33,382 - MAKE_MOSAIC - INFO - Checking for images and beams
2022-04-12 15:25:33,383 - MAKE_MOSAIC - ERROR - File output_short/cubes/cube_1/BLABLABLA.fits does not exist
Traceback (most recent call last):
  File "/home/pserra/Astro/caracal-venv-3.7/lib/python3.7/site-packages/mosaicQueen/main.py", line 32, in check_for_files
    open(directory+'/'+ff)
FileNotFoundError: [Errno 2] No such file or directory: 'output_short/cubes/cube_1/BLABLABLA.fits'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pserra/Astro/caracal-venv-3.7/bin/mosaic-queen", line 8, in <module>
    main.main(sys.argv[1:])
  File "/home/pserra/Astro/caracal-venv-3.7/lib/python3.7/site-packages/mosaicQueen/main.py", line 128, in main
    check_for_files(input_dir, images, 'images', args.regrid)  # This raises an error and exits if files are not found
  File "/home/pserra/Astro/caracal-venv-3.7/lib/python3.7/site-packages/mosaicQueen/main.py", line 37, in check_for_files
    raise FileNotFoundError
FileNotFoundError
```

**Comment by sphemakh** [comment]
That looks good to me. Maybe the check for these files was added after I raised an issue.
