### ISSUE TITLE
No such file or directory: 'mImgtbl'

### ISSUE THREAD

**Issue by Athanaseus** [caracal-pipeline/MosaicQueen#29]
Hi, I'm trying to run mosaic queen and I'm getting No such file or directory: 'mImgtbl'

Running:
```
mosaic-queen --mosaic-type spectral --name mymosaic --associated-mosaic --force-regrid --beam-cutoff 0.1 --mosaic-cutoff 0.2 --statistic mad --guess-std 0.01 --input input --target-images mos_T29R03C01_HI.image.fits mos_T29R03C03_HI.image.fits mos_T29R04C02_HI.image.fits --output output
```
gives the following output:
```
mosaic-queen --mosaic-type spectral --name mymosaic --associated-mosaic --force-regrid --beam-cutoff 0.1 --mosaic-cutoff 0.2 --statistic mad --guess-std 0.01 --input input --target-images mos_T29R03C01_HI.image.fits mos_T29R03C03_HI.image.fits mos_T29R04C02_HI.image.fits --output output
2022-05-09 15:23:44,165 - MAKE_MOSAIC - INFO - Target images = mos_T29R03C01_HI.image.fits mos_T29R03C03_HI.image.fits mos_T29R04C02_HI.image.fits
2022-05-09 15:23:44,165 - MAKE_MOSAIC - INFO - Will generate mosaics made from the input images, their associated models, and their residuals
2022-05-09 15:23:44,165 - MAKE_MOSAIC - INFO - Checking for images and beams
2022-05-09 15:23:44,166 - MAKE_MOSAIC - INFO - All images found on disk
2022-05-09 15:23:44,166 - MAKE_MOSAIC - INFO - All beams found on disk
2022-05-09 15:23:44,166 - MAKE_MOSAIC - INFO - Checking for models and residuals
2022-05-09 15:23:44,166 - MAKE_MOSAIC - INFO - All models found on disk
2022-05-09 15:23:44,166 - MAKE_MOSAIC - INFO - All residuals found on disk
2022-05-09 15:23:44,171 - MAKE_MOSAIC - INFO - You have asked for all regridded files to be created by this run, even if they are already on disk
2022-05-09 15:23:44,171 - MAKE_MOSAIC - INFO - Running montage tasks to create mosaic header ...
2022-05-09 15:23:44,171 - MAKE_MOSAIC - INFO -       mImgtbl -t output/mymosaic_image_fields input output/mymosaic_image_fields.tbl
Traceback (most recent call last):
  File "/home/athanaseus/.virtualenvs/mosaic-queen/bin/mosaic-queen", line 8, in <module>
    main.main(sys.argv[1:])
  File "/home/athanaseus/.virtualenvs/mosaic-queen/lib/python3.8/site-packages/mosaicQueen/main.py", line 142, in main
    make_mosaic.use_montage_for_regridding(
  File "/home/athanaseus/.virtualenvs/mosaic-queen/lib/python3.8/site-packages/mosaicQueen/make_mosaic.py", line 93, in use_montage_for_regridding
    Run('mImgtbl -t {0:s}/{1:s}_{2:s}_fields {3:s} {0:s}/{1:s}_{2:s}_fields.tbl'.format(output_dir,outname,image_type,input_dir))
  File "/home/athanaseus/.virtualenvs/mosaic-queen/lib/python3.8/site-packages/mosaicQueen/make_mosaic.py", line 46, in Run
    result = subprocess.check_output(command.split())
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'mImgtbl'

```

**Comment by paoloserra** [comment]
Maybe it's related to #17 ?

**Comment by Athanaseus** [comment]
This should be resolve by:

```sudo apt install montage```

Instruction now in README.

**Comment by paoloserra** [comment]
Will a Stimela / CARACal user also need to install montage seprately?

**Comment by Athanaseus** [comment]
> Will a Stimela / CARACal user also need to install montage seprately?

- No, this will be available in the container. Only for users using it independently.

**Comment by paoloserra** [comment]
ok, cool
