### ISSUE TITLE
MosaicSteward running out of memory

### ISSUE THREAD

**Issue by paoloserra** [caracal-pipeline/MosaicQueen#9]
Hi @svw26, here's this error I'm getting (within CARACal) when adding the 12th (out of 23) cubes to the mosaic. Previous mosaic runs with smaller cubes went well, so I'm tentatively guessing it's got to do with the cubes size. But honestly I don't really know what's up. Any ideas?

(Incidentally, I'm puzzled by the reference to python2.7 in the error.)

```
# 2021-02-06 11:25:02,540 - MAKE_MOSAIC - INFO - Adding t15_1kms_mfs05_HI.imageR.fits to the mosaic ...
# 2021-02-06 11:46:50,782 - MAKE_MOSAIC - INFO - Adding t15_1kms_mfs06_HI.imageR.fits to the mosaic ...
# 2021-02-06 12:12:08,117 - MAKE_MOSAIC - INFO - Adding t15_1kms_mfs07_HI.imageR.fits to the mosaic ...
# 2021-02-06 12:30:50,323 - MAKE_MOSAIC - INFO - Adding t15_1kms_mfs10_HI.imageR.fits to the mosaic ...
# 2021-02-06 12:56:01,816 - MAKE_MOSAIC - INFO - Adding t15_1kms_mfs11_HI.imageR.fits to the mosaic ...
# 2021-02-06 13:17:10,932 - MAKE_MOSAIC - INFO - Adding t15_1kms_mfs12_HI.imageR.fits to the mosaic ...
# 2021-02-06 13:37:13,355 - MAKE_MOSAIC - INFO - Adding t15_1kms_mfs13_HI.imageR.fits to the mosaic ...
# 2021-02-06 13:57:09,096 - MAKE_MOSAIC - INFO - Adding t15_1kms_mfs16_HI.imageR.fits to the mosaic ...
# 2021-02-06 14:20:05,818 - MAKE_MOSAIC - INFO - Adding t15_1kms_mfs17_HI.imageR.fits to the mosaic ...
# 2021-02-06 14:40:26,848 - MAKE_MOSAIC - INFO - Adding t15_1kms_mfs18_HI.imageR.fits to the mosaic ...
# 2021-02-06 15:03:20,760 - MAKE_MOSAIC - INFO - Adding t15_1kms_mfs19_HI.imageR.fits to the mosaic ...
# 2021-02-06 15:26:57,765 - MAKE_MOSAIC - INFO - Adding t15_1kms_mfs23_HI.imageR.fits to the mosaic ...
# Traceback (most recent call last):
#   File "/stimela_mount/code/run.py", line 49, in <module>
#     subprocess.check_call(shlex.split(_runc))
#   File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
#     raise CalledProcessError(retcode, cmd)
# subprocess.CalledProcessError: Command '['MosaicSteward', '--mosaic-type', 'spectral', '--domontage', '--cutoff', '0.1', '--name', 't15_1kms', '--input', '/stimela_mount/input/mos_output/cubes', '--target-images', 't15_1kms_mfs05_HI.image.fits', '--target-images', 't15_1kms_mfs06_HI.image.fits', '--target-images', 't15_1kms_mfs07_HI.image.fits', '--target-images', 't15_1kms_mfs10_HI.image.fits', '--target-images', 't15_1kms_mfs11_HI.image.fits', '--target-images', 't15_1kms_mfs12_HI.image.fits', '--target-images', 't15_1kms_mfs13_HI.image.fits', '--target-images', 't15_1kms_mfs16_HI.image.fits', '--target-images', 't15_1kms_mfs17_HI.image.fits', '--target-images', 't15_1kms_mfs18_HI.image.fits', '--target-images', 't15_1kms_mfs19_HI.image.fits', '--target-images', 't15_1kms_mfs23_HI.image.fits', '--target-images', 't15_1kms_mfs24_HI.image.fits', '--target-images', 't15_1kms_mfs25_HI.image.fits', '--target-images', 't15_1kms_mfs26_HI.image.fits', '--target-images', 't15_1kms_mfs31_HI.image.fits', '--target-images', 't15_1kms_mfs32_HI.image.fits', '--target-images', 't15_1kms_mfs33_HI.image.fits', '--target-images', 't15_1kms_mfs37_HI.image.fits', '--target-images', 't15_1kms_mfs38_HI.image.fits', '--target-images', 't15_1kms_mfs39_HI.image.fits', '--target-images', 't15_1kms_mfs43_HI.image.fits', '--target-images', 't15_1kms_mfs44_HI.image.fits', '--output', '/stimela_mount/output']' returned non-zero exit status -9
2021-02-06 17:34:50 CARACal.Stimela.mosaic-steward ERROR: cd /scratch3/projects/fornax/data_reduction/.stimela_workdir-16124677923335197 && singularity returns error code 1
2021-02-06 17:34:50 CARACal.Stimela.mosaic-steward ERROR: job failed at 2021-02-06 17:34:50.771411 after 1 day, 19:51:25.894855
2021-02-06 17:34:51 CARACal.Stimela.mosaic-steward ERROR: Traceback (most recent call last):
2021-02-06 17:34:51 CARACal.Stimela.mosaic-steward ERROR:   File "/idia/projects/fornax/caracal-venv/lib/python3.6/site-packages/stimela/recipe.py", line 703, in run
2021-02-06 17:34:51 CARACal.Stimela.mosaic-steward ERROR:     job.run_job()
2021-02-06 17:34:51 CARACal.Stimela.mosaic-steward ERROR:   File "/idia/projects/fornax/caracal-venv/lib/python3.6/site-packages/stimela/recipe.py", line 418, in run_job
2021-02-06 17:34:51 CARACal.Stimela.mosaic-steward ERROR:     self.job.run(output_wrangler=self.apply_output_wranglers)
2021-02-06 17:34:51 CARACal.Stimela.mosaic-steward ERROR:   File "/idia/projects/fornax/caracal-venv/lib/python3.6/site-packages/stimela/singularity.py", line 128, in run
2021-02-06 17:34:51 CARACal.Stimela.mosaic-steward ERROR:     env=self._env, logfile=self.logfile)
2021-02-06 17:34:51 CARACal.Stimela.mosaic-steward ERROR:   File "/idia/projects/fornax/caracal-venv/lib/python3.6/site-packages/stimela/utils/xrun_poll.py", line 227, in xrun
2021-02-06 17:34:51 CARACal.Stimela.mosaic-steward ERROR:     raise StimelaCabRuntimeError("{} returns error code {}".format(command_name, status))
2021-02-06 17:34:51 CARACal.Stimela.mosaic-steward ERROR: stimela.utils.StimelaCabRuntimeError: cd /scratch3/projects/fornax/data_reduction/.stimela_workdir-16124677923335197 && singularity returns error code 1
2021-02-06 17:34:51 CARACal.Stimela.mosaic INFO: Completed jobs : ['cdelt3_check']
2021-02-06 17:34:51 CARACal.Stimela.mosaic INFO: Remaining jobs : []
2021-02-06 17:34:51 CARACal.Stimela.mosaic INFO: Saving pipeline information in .last_mosaic.json
2021-02-06 17:34:51 CARACal ERROR: Job 'MosaicSteward:: Re-gridding spectral images before mosaicking them. For this mode, the mosaic_worker is using *pb.fits files generated by the line_worker.' failed: cd /scratch3/projects/fornax/data_reduction/.stimela_workdir-16124677923335197 && singularity returns error code 1 [PipelineException]
2021-02-06 17:34:51 CARACal INFO:   More information can be found in the logfile at mos_output/logs-20210204-214256/log-caracal.txt
2021-02-06 17:34:51 CARACal INFO:   You are running version 1.0.4
2021-02-06 17:34:51 CARACal ERROR: Traceback (most recent call last):
2021-02-06 17:34:51 CARACal ERROR:   File "/idia/projects/fornax/caracal-venv/lib/python3.6/site-packages/caracal/main.py", line 183, in __run
2021-02-06 17:34:51 CARACal ERROR:     pipeline.run_workers()
2021-02-06 17:34:51 CARACal ERROR:   File "/idia/projects/fornax/caracal-venv/lib/python3.6/site-packages/caracal/workers/worker_administrator.py", line 413, in run_workers
2021-02-06 17:34:51 CARACal ERROR:     worker.worker(self, recipe, config)
2021-02-06 17:34:51 CARACal ERROR:   File "/idia/projects/fornax/caracal-venv/lib/python3.6/site-packages/caracal/workers/mosaic_worker.py", line 423, in worker
2021-02-06 17:34:51 CARACal ERROR:     recipe.run()
2021-02-06 17:34:51 CARACal ERROR:   File "/idia/projects/fornax/caracal-venv/lib/python3.6/site-packages/stimela/recipe.py", line 754, in run
2021-02-06 17:34:51 CARACal ERROR:     raise PipelineException(exc, self.completed, job, self.remaining) from None
2021-02-06 17:34:51 CARACal ERROR: stimela.exceptions.PipelineException: Job 'MosaicSteward:: Re-gridding spectral images before mosaicking them. For this mode, the mosaic_worker is using *pb.fits files generated by the line_worker.' failed: cd /scratch3/projects/fornax/data_reduction/.stimela_workdir-16124677923335197 && singularity returns error code 1
2021-02-06 17:34:51 CARACal INFO: exiting with error code 1
```

**Comment by paoloserra** [comment]
Update -- I think the process just ran out of memory.

Since in principle I have enough RAM to store the mosaic numpy array and one image+beam pair, the problem may be with the lines https://github.com/svw26/MosaicSteward/blob/e7cdb4f5dbb30af7cceeabb641691b5a086b40cc/MosaicSteward/make_mosaic.py#L152-L156

I'm now testing a stand-alone code that  does the same but using Python's `with` statement to open the image+beam FITS files.

**Comment by paoloserra** [comment]
Well, using `with` didn't help :(

Given #10 I'm now converting to `BITPIX = -32` and trying again.

**Comment by svw26** [comment]
Hiya @paoloserra. Yes, I agree that it is to do with running out of memory. At the end of the Traceback is "returned non-zero exit status -9", which leads me to this page: https://forum.qiime2.org/t/vsearch-returned-non-zero-exit-status-9-probably-due-to-trying-to-use-too-many-threads/6395 

For reference, when you've run it with smaller cubes, what was the largest number of component images where it still worked? 23, as in this case? x

**Comment by paoloserra** [comment]
Yes, I could run it on 23 smaller cubes with no problems.

**Comment by paoloserra** [comment]
btw, converting to `BITPIX = -32` worked for this  particular case, but it will most likely break with larger cubes.

**Comment by paoloserra** [comment]
Besides improving the way  in which we open files etc, we should also use @gigjozsa suggestion at https://github.com/svw26/MosaicSteward/issues/10#issuecomment-779784096 to load data as 32 bit arrays even when montage has regridded to 64 bit arrays.

**Comment by paoloserra** [comment]
@SpheMakh @svw26 I continued having memory problems with my large mosaic.

I'm finding that the following implementation of the coadding part of the code has better memory footprint than current MosaicSteward. It allowed me to coadd 24 x 18 GB  cube (each with its 18 GB primary  beam cube) and create a 77 GB mosaic cube and a 77 GB noise cube with 232 GB of available RAM.

Note that 3*77 GB = 231 GB, and from the RAM usage monitoring it looks like I just made it. So it seems that the RAM footprint of the code below is 3 x the final mosaic.

```
    for ii, bb in zip(imagesR, beamsR):
        print('Adding {0:s} to the mosaic ...'.format(ii))
        with fits.open(output_dir+'/'+ii) as f, fits.open(output_dir+'/'+bb) as g:  # i.e. open a specific re-gridded image and beam
            head = f[0].header
            y1 = int(float(moshead['CRPIX2']) - head['CRPIX2'])
            y2 = int(float(moshead['CRPIX2']) - head['CRPIX2'] + head['NAXIS2'])
            x1 = int(float(moshead['CRPIX1']) - head['CRPIX1'])
            x2 = int(float(moshead['CRPIX1']) - head['CRPIX1'] + head['NAXIS1'])
            # mosaicking with no PB correction
            # norm_array[:,y1:y2,x1:x2]+=~np.isnan(f[0].data)
            # mos_array[:,y1:y2,x1:x2]+=np.nan_to_num(f[0].data)
            # mosaicking with PB correction
            if mosaic_type == 'spectral':
                A = np.nan_to_num(g[0].data)
                B = A > cutoff
                C = np.nan_to_num(f[0].data)
                norm_array[:, y1:y2, x1:x2] += (A * B)**2
                mos_array[:, y1:y2, x1:x2] += C * A * B
                del A
                del B
                del C

#                norm_array[:, y1:y2, x1:x2] += (np.nan_to_num(g[0].data)
#                                          * (np.nan_to_num(g[0].data) > cutoff))**2
#                mos_array[:, y1:y2, x1:x2] += np.nan_to_num(f[0].data)*np.nan_to_num(
#                    g[0].data)*(np.nan_to_num(g[0].data) > cutoff)

            if mosaic_type == 'continuum':
                norm_array[y1:y2, x1:x2] += (np.nan_to_num(g[0].data)
                                          * (np.nan_to_num(g[0].data) > cutoff))**2
                mos_array[y1:y2, x1:x2] += np.nan_to_num(f[0].data)*np.nan_to_num(
                    g[0].data)*(np.nan_to_num(g[0].data) > cutoff)

    norm_array[norm_array == 0] = np.nan

    moshead = make_mosaic_header(mosaic_type, moshead)
    if mosaic_type == 'spectral':
        with fits.open(input_dir+'/'+images[0]) as f:
            zhead = f[0].header
            moshead['ctype3'] = zhead['ctype3']

    mos_array /= norm_array
    fits.writeto('{0:s}/{1:s}.fits'.format(output_dir,outname), mos_array, overwrite=True, header=moshead)
    del mos_array

    norm_array **= -0.5 # take 1/np.sqrt(norm_array)
    fits.writeto('{0:s}/{1:s}_noise.fits'.format(output_dir,outname), norm_array, overwrite=True, header=moshead)
    del norm_array

    print('The following mosaic FITS were written to disc: {0:s}.fits {0:s}_noise.fits {0:s}_weights.fits'.format(outname))
    print('Mosaicking completed')
```

**Comment by sphemakh** [comment]
Is there a set of images I can use to test my changes? 

see branch [issue-9](https://github.com/svw26/MosaicSteward/tree/issue-9 ) if you interested

**Comment by svw26** [comment]
I have images (cubes + beams) in here, on nash: /home/sarahwhite/test_montage_mosaic/user_input

They are small, for running quick tests, but you might want something larger. x

**Comment by sphemakh** [comment]
My tests are running, but this was just to check for coding errors. @paoloserra or @svw26 can you test branch `issue-9`

**Comment by svw26** [comment]
I can, but I don't know to profile memory usage ( ...so if you have something I could use on nash...?) x

**Comment by sphemakh** [comment]
The manual way is the `htop` command. @paoloserra, how were you tracking it?

**Comment by paoloserra** [comment]
this time around I was on ilifu and was using their grafana monitors

otherwise normally I just do `top -b -n 86400 -u <user> -d 1 > <outputfile>` but then it takes a few lines of code to extract and plot the relevant info.

**Comment by paoloserra** [comment]
I will send a plotting script I've got via email, haven't used it in a while though...

**Comment by sphemakh** [comment]
From watching `htop` on my laptop I don't see a significant change in memory usage as the loop iterates over the images. Note, I have no parallelized it yet.

@paoloserra maybe it's faster if you do the test on the images that were causing a problem.

**Comment by paoloserra** [comment]
sorry mate, but it won't be fast, it takes several hours for things to crash, and I won't be able to get to this before wednesday

**Comment by sphemakh** [comment]
OK, I'll wait for feedback from either of you

**Comment by svw26** [comment]
Hiya @SpheMakh, I fetched a copy of the issue-9 branch and installed it locally. It runs through fine with the command:

```MosaicSteward --mosaic-type spectral --domontage --cutoff 0.25 --name fromPaolo --input user_input --target-images j0831-5517-ska_HI.image.fits --target-images j0836-5552-ska_HI.image.fits --target-images j0839-5517-ska_HI.image.fits --output user_output```

completing within 15 minutes, just as the master branch does. 

Note that the majority of the time is spent on re-gridding, so once you have a set of re-gridded images and beams in place, you could drop the ```--domontage``` switch for following runs in order to really test the mosaicking part.

Attached are the 'top' files from running with master and running with the issue-9 branch. When I run them with @paoloserra's plotting script I just get an interactive window with no data, so not sure what's up... x
 
[topinfo_MosaicSteward_master_3D.txt](https://github.com/svw26/MosaicSteward/files/6027809/topinfo_MosaicSteward_master_3D.txt)
[topinfo_MosaicSteward_issue9_3D.txt](https://github.com/svw26/MosaicSteward/files/6027810/topinfo_MosaicSteward_issue9_3D.txt)

**Comment by sphemakh** [comment]
Pinging @sjperkins

**Comment by sjperkins** [comment]
Open with the `memmap=True` option and slice the data attribute of the HDU object.

https://docs.astropy.org/en/stable/io/fits/index.html#working-with-large-files
